# este archivo permite que cada desarrollo (proyecto de gitlab) tenga su propio pipeline
docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    # las variables de entorno "$LOQUESEA" hay que agregarlas en gitlab (settings->CI/CD->Variables)
    # se conecta a docker-hub 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    # construye la imagen de docker-php-app 
    - docker build --pull -t "$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA" .
    # la sube a docker-hub
    - docker push "$CI_REGISTRY_IMAGE"
  variables:
    # esto permite que el runner se conecte al demonio de docker de kubernetes
    DOCKER_HOST: tcp://localhost:2375
    DOCKER_TLS_CERTDIR: ""

# ejecucion de kubernetes
deploy:
  stage: deploy
  image: bitnami/kubectl
  script:
    # comprueba si el deploy hola-php existe sino lo crea a partir de la imagen anterior
    - kubectl get deployment hola-php || kubectl create deployment hola-php --image="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    # si la imagen ya esta creada directamente viene a este paso y la actualiza
    - kubectl set image deployment/hola-php hola-php="$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
